const CONSTITUENCIES = [
  // Ashanti (47)
  { id: 'suame', name: 'Suame', region: 'Ashanti', party: 'NPP', mpName: 'Osei Kyei-Mensah' },
  { id: 'adansi-asokwa', name: 'Adansi-Asokwa', region: 'Ashanti', party: 'NPP', mpName: 'Kobina Tahir Hammond' },
  { id: 'afigya-kwabre-north', name: 'Afigya Kwabre North', region: 'Ashanti', party: 'NPP', mpName: 'Collins Adomako-Mensah' },
  { id: 'afigya-kwabre-south', name: 'Afigya Kwabre South', region: 'Ashanti', party: 'NPP', mpName: 'William Owuraku Aidoo' },
  { id: 'afigya-sekyere-east', name: 'Afigya Sekyere East', region: 'Ashanti', party: 'NPP', mpName: 'Mavis Nkansah Boadu' },
  { id: 'ahafo-ano-north', name: 'Ahafo Ano North', region: 'Ashanti', party: 'NDC', mpName: 'Suleman Adamu Sanid' },
  { id: 'ahafo-ano-south-east', name: 'Ahafo Ano South East', region: 'Ashanti', party: 'NPP', mpName: 'Yaw Owusu Adjei' },
  { id: 'ahafo-ano-south-west', name: 'Ahafo Ano South West', region: 'Ashanti', party: 'NPP', mpName: 'Johnson Kwaku Adu' },
  { id: 'akrofuom', name: 'Akrofuom', region: 'Ashanti', party: 'NPP', mpName: 'Alex Blankson' },
  { id: 'asante-akim-central', name: 'Asante Akim Central', region: 'Ashanti', party: 'NPP', mpName: 'Kwame Anyimadu-Antwi' },
  { id: 'asante-akim-north', name: 'Asante Akim North', region: 'Ashanti', party: 'NPP', mpName: 'Andy Appiah-Kubi' },
  { id: 'asante-akim-south', name: 'Asante Akim South', region: 'Ashanti', party: 'NPP', mpName: 'Kwadwo Asante' },
  { id: 'asawase', name: 'Asawase', region: 'Ashanti', party: 'NDC', mpName: 'Muntaka Mubarak' },
  { id: 'asokwa', name: 'Asokwa', region: 'Ashanti', party: 'NPP', mpName: 'Patricia Appiagyei' },
  { id: 'atwima-kwanwoma', name: 'Atwima Kwanwoma', region: 'Ashanti', party: 'NPP', mpName: 'Kofi Amankwa-Mani' },
  { id: 'atwima-mponua', name: 'Atwima Mponua', region: 'Ashanti', party: 'NPP', mpName: 'Isaac Asiamah' },
  { id: 'atwima-nwabiagya-north', name: 'Atwima Nwabiagya North', region: 'Ashanti', party: 'NPP', mpName: 'Benito Owusu Bio' },
  { id: 'atwima-nwabiagya-south', name: 'Atwima Nwabiagya South', region: 'Ashanti', party: 'NPP', mpName: 'Emmanuel Agyei Anhwere' },
  { id: 'bantama', name: 'Bantama', region: 'Ashanti', party: 'NPP', mpName: 'Francis Asenso-Boakye' },
  { id: 'bekwai', name: 'Bekwai', region: 'Ashanti', party: 'NPP', mpName: 'Joseph Osei-Owusu' },
  { id: 'bosome-freho', name: 'Bosome Freho', region: 'Ashanti', party: 'NPP', mpName: 'Akwasi Darko Boateng' },
  { id: 'bosomtwe', name: 'Bosomtwe', region: 'Ashanti', party: 'NPP', mpName: 'Yaw Osei Adutwum' },
  { id: 'effiduase-asokore', name: 'Effiduase-Asokore', region: 'Ashanti', party: 'NPP', mpName: 'Nana Ayew Afriye' },
  { id: 'ejisu', name: 'Ejisu', region: 'Ashanti', party: 'NPP', mpName: 'John Ampontuah Kumah' },
  { id: 'ejura-sekyedumase', name: 'Ejura Sekyedumase', region: 'Ashanti', party: 'NDC', mpName: 'Muhammad Bawah Braimah' },
  { id: 'fomena', name: 'Fomena', region: 'Ashanti', party: 'Independent', mpName: 'Andrew Asiamah Amoako' },
  { id: 'juaben', name: 'Juaben', region: 'Ashanti', party: 'NPP', mpName: 'Ama Pomaa Boateng' },
  { id: 'kumawu', name: 'Kumawu', region: 'Ashanti', party: 'NPP', mpName: 'Ernest Yaw Anim' },
  { id: 'kwabre-east', name: 'Kwabre East', region: 'Ashanti', party: 'NPP', mpName: 'Francisca Oteng Mensah' },
  { id: 'kwadaso', name: 'Kwadaso', region: 'Ashanti', party: 'NPP', mpName: 'Kingsley Nyarko' },
  { id: 'mampong', name: 'Mampong', region: 'Ashanti', party: 'NPP', mpName: 'Kwaku Ampratwum-Sarpong' },
  { id: 'manhyia-north', name: 'Manhyia North', region: 'Ashanti', party: 'NPP', mpName: 'Akwasi Konadu' },
  { id: 'manhyia-south', name: 'Manhyia South', region: 'Ashanti', party: 'NPP', mpName: 'Matthew Opoku Prempeh' },
  { id: 'manso-adubia', name: 'Manso Adubia', region: 'Ashanti', party: 'NPP', mpName: 'Yaw Frimpong Addo' },
  { id: 'manso-nkwanta', name: 'Manso Nkwanta', region: 'Ashanti', party: 'NPP', mpName: 'George Obeng Takyi' },
  { id: 'new-edubiase', name: 'New Edubiase', region: 'Ashanti', party: 'NDC', mpName: 'Adams Abdul Salam' },
  { id: 'nhyiaeso', name: 'Nhyiaeso', region: 'Ashanti', party: 'NPP', mpName: 'Stephen Amoah' },
  { id: 'nsuta-kwamang-beposo', name: 'Nsuta-Kwamang-Beposo', region: 'Ashanti', party: 'NPP', mpName: 'Adelaide Ntim' },
  { id: 'obuasi-east', name: 'Obuasi East', region: 'Ashanti', party: 'NPP', mpName: 'Dr. Patrick Boakye-Yiadom' },
  { id: 'obuasi-west', name: 'Obuasi West', region: 'Ashanti', party: 'NPP', mpName: 'Kwaku Kwarteng' },
  { id: 'odotobri', name: 'Odotobri', region: 'Ashanti', party: 'NPP', mpName: 'Emmanuel Akwasi Gyamfi' },
  { id: 'offinso-north', name: 'Offinso North', region: 'Ashanti', party: 'NPP', mpName: 'Augustine Collins Ntim' },
  { id: 'offinso-south', name: 'Offinso South', region: 'Ashanti', party: 'NPP', mpName: 'Isaac Yaw Opoku' },
  { id: 'oforikrom', name: 'Oforikrom', region: 'Ashanti', party: 'NPP', mpName: 'Emmanuel Marfo' },
  { id: 'old-tafo', name: 'Old Tafo', region: 'Ashanti', party: 'NPP', mpName: 'Vincent Ekow Assafuah' },
  { id: 'sekyere-afram-plains', name: 'Sekyere Afram Plains', region: 'Ashanti', party: 'NDC', mpName: 'Alex Adomako-Mensah' },
  { id: 'subin', name: 'Subin', region: 'Ashanti', party: 'NPP', mpName: 'Eugene Boakye Antwi' },

  // Greater Accra (34)
  { id: 'ablekuma-central', name: 'Ablekuma Central', region: 'Greater Accra', party: 'NDC', mpName: 'Dan Abdul-Latif' },
  { id: 'ablekuma-north', name: 'Ablekuma North', region: 'Greater Accra', party: 'NPP', mpName: 'Sheila Bartels' },
  { id: 'ablekuma-south', name: 'Ablekuma South', region: 'Greater Accra', party: 'NDC', mpName: 'Alfred Oko Vanderpuije' },
  { id: 'ablekuma-west', name: 'Ablekuma West', region: 'Greater Accra', party: 'NPP', mpName: 'Ursula Owusu-Ekuful' },
  { id: 'adentan', name: 'Adentan', region: 'Greater Accra', party: 'NDC', mpName: 'Mohammed Ramadan' },
  { id: 'amasaman', name: 'Amasaman', region: 'Greater Accra', party: 'NPP', mpName: 'Akwasi Patrick Nsiah' },
  { id: 'anyaa-sowutuom', name: 'Anyaa-Sowutuom', region: 'Greater Accra', party: 'NPP', mpName: 'Dickson Adomako Kissi' },
  { id: 'ashaiman', name: 'Ashaiman', region: 'Greater Accra', party: 'NDC', mpName: 'Ernest Henry Norgbey' },
  { id: 'ayawaso-central', name: 'Ayawaso Central', region: 'Greater Accra', party: 'NPP', mpName: 'Henry Quartey' },
  { id: 'ayawaso-east', name: 'Ayawaso East', region: 'Greater Accra', party: 'NDC', mpName: 'Naser Toure Mahama' },
  { id: 'ayawaso-north', name: 'Ayawaso North', region: 'Greater Accra', party: 'NDC', mpName: 'Yussif Jajah' },
  { id: 'ayawaso-west-wuogon', name: 'Ayawaso West Wuogon', region: 'Greater Accra', party: 'NPP', mpName: 'Lydia Alhassan' },
  { id: 'bortianor-ngleshie-amanfro', name: 'Bortianor Ngleshie Amanfro', region: 'Greater Accra', party: 'NPP', mpName: 'Sylvester Tetteh' },
  { id: 'la-dade-kotopon', name: 'La Dade Kotopon', region: 'Greater Accra', party: 'NDC', mpName: 'Rita Odoley Sowah' },
  { id: 'dome-kwabenya', name: 'Dome Kwabenya', region: 'Greater Accra', party: 'NPP', mpName: 'Sarah Adwoa Safo' },
  { id: 'domeabra-obom', name: 'Domeabra Obom', region: 'Greater Accra', party: 'NDC', mpName: 'Sophia Karen Ackuaku' },
  { id: 'korle-klottey', name: 'Korle Klottey', region: 'Greater Accra', party: 'NDC', mpName: 'Zanetor Agyeman-Rawlings' },
  { id: 'kpone-katamanso', name: 'Kpone Katamanso', region: 'Greater Accra', party: 'NDC', mpName: 'Joseph Akuerteh Tettey' },
  { id: 'krowor', name: 'Krowor', region: 'Greater Accra', party: 'NDC', mpName: 'Agnes Naa Momo Lartey' },
  { id: 'ledzokuku', name: 'Ledzokuku', region: 'Greater Accra', party: 'NDC', mpName: 'Benjamin Ayiku Narteh' },
  { id: 'madina', name: 'Madina', region: 'Greater Accra', party: 'NDC', mpName: 'Francis-Xavier Sosu' },
  { id: 'ningo-prampram', name: 'Ningo Prampram', region: 'Greater Accra', party: 'NDC', mpName: 'Sam Nartey George' },
  { id: 'odododiodio', name: 'Odododiodio', region: 'Greater Accra', party: 'NDC', mpName: 'Edwin Nii Lante Vanderpuye' },
  { id: 'okaikwei-central', name: 'Okaikwei Central', region: 'Greater Accra', party: 'NPP', mpName: 'Patrick Yaw Boamah' },
  { id: 'okaikwei-north', name: 'Okaikwei North', region: 'Greater Accra', party: 'NDC', mpName: 'Theresa Lardi Awuni' },
  { id: 'okaikwei-south', name: 'Okaikwei South', region: 'Greater Accra', party: 'NPP', mpName: 'Dakoa Newman' },
  { id: 'sege', name: 'Sege', region: 'Greater Accra', party: 'NDC', mpName: 'Christian Corleytey Otuteye' },
  { id: 'shai-osudoku', name: 'Shai Osudoku', region: 'Greater Accra', party: 'NDC', mpName: 'Linda Ocloo' },
  { id: 'tema-central', name: 'Tema Central', region: 'Greater Accra', party: 'NPP', mpName: 'Yves Hanson-Nortey' },
  { id: 'tema-east', name: 'Tema East', region: 'Greater Accra', party: 'NDC', mpName: 'Isaac Ashai Odamtten' },
  { id: 'tema-west', name: 'Tema West', region: 'Greater Accra', party: 'NPP', mpName: 'Carlos Kingsley Ahenkorah' },
  { id: 'trobu', name: 'Trobu', region: 'Greater Accra', party: 'NPP', mpName: 'Moses Anim' },
  { id: 'weija-gbawe', name: 'Weija Gbawe', region: 'Greater Accra', party: 'NPP', mpName: 'Tina Gifty Naa Ayeley Mensah' },

  // Eastern (33)
  { id: 'abetifi', name: 'Abetifi', region: 'Eastern', party: 'NPP', mpName: 'Bryan Acheampong' },
  { id: 'abirem', name: 'Abirem', region: 'Eastern', party: 'NPP', mpName: 'John Frimpong Osei' },
  { id: 'abuakwa-north', name: 'Abuakwa North', region: 'Eastern', party: 'NPP', mpName: 'Gifty Twum Ampofo' },
  { id: 'abuakwa-south', name: 'Abuakwa South', region: 'Eastern', party: 'NPP', mpName: 'Samuel Atta Akyea' },
  { id: 'achiase', name: 'Achiase', region: 'Eastern', party: 'NPP', mpName: 'Kofi Ahenkorah Marfo' },
  { id: 'afram-plains-north', name: 'Afram Plains North', region: 'Eastern', party: 'NDC', mpName: 'Betty Krosbi Mensah' },
  { id: 'afram-plains-south', name: 'Afram Plains South', region: 'Eastern', party: 'NDC', mpName: 'Joseph Appiah Boateng' },
  { id: 'akim-oda', name: 'Akim Oda', region: 'Eastern', party: 'NPP', mpName: 'Alexander Akwasi Acquah' },
  { id: 'akim-swedru', name: 'Akim Swedru', region: 'Eastern', party: 'NPP', mpName: 'Kennedy Osei Nyarko' },
  { id: 'akropong', name: 'Akropong', region: 'Eastern', party: 'NPP', mpName: 'Nana Ama Dokua Asiamah Adjei' },
  { id: 'akwatia', name: 'Akwatia', region: 'Eastern', party: 'NDC', mpName: 'Henry Yiadom Boakye' },
  { id: 'asene-akroso-manso', name: 'Asene Akroso-Manso', region: 'Eastern', party: 'NPP', mpName: 'George Kwame Aboagye' },
  { id: 'asuogyaman', name: 'Asuogyaman', region: 'Eastern', party: 'NDC', mpName: 'Thomas Ampem Nyarko' },
  { id: 'atiwa-east', name: 'Atiwa East', region: 'Eastern', party: 'NPP', mpName: 'Abena Osei-Asare' },
  { id: 'atiwa-west', name: 'Atiwa West', region: 'Eastern', party: 'NPP', mpName: 'Kwasi Amoako-Attah' },
  { id: 'ayensuano', name: 'Ayensuano', region: 'Eastern', party: 'NDC', mpName: 'Teddy Safori Addi' },
  { id: 'fanteakwa-north', name: 'Fanteakwa North', region: 'Eastern', party: 'NPP', mpName: 'Kwabena Amankwah Asiamah' },
  { id: 'fanteakwa-south', name: 'Fanteakwa South', region: 'Eastern', party: 'NPP', mpName: 'Kofi Okyere Agyekum' },
  { id: 'kade', name: 'Kade', region: 'Eastern', party: 'NPP', mpName: 'Alexander Agyare' },
  { id: 'lower-manya-krobo', name: 'Lower Manya Krobo', region: 'Eastern', party: 'NDC', mpName: 'Ebenezer Okletey Terlabi' },
  { id: 'lower-west-akim', name: 'Lower West Akim', region: 'Eastern', party: 'NPP', mpName: 'Charles Acheampong' },
  { id: 'mpraeso', name: 'Mpraeso', region: 'Eastern', party: 'NPP', mpName: 'Davis Ansah Opoku' },
  { id: 'new-juaben-north', name: 'New Juaben North', region: 'Eastern', party: 'NPP', mpName: 'Nana Adjei Boateng' },
  { id: 'new-juaben-south', name: 'New Juaben South', region: 'Eastern', party: 'NPP', mpName: 'Michael Okyere Baafi' },
  { id: 'nsawam-adoagyiri', name: 'Nsawam Adoagyiri', region: 'Eastern', party: 'NPP', mpName: 'Frank Annoh-Dompreh' },
  { id: 'ofoase-ayirebi', name: 'Ofoase-Ayirebi', region: 'Eastern', party: 'NPP', mpName: 'Kojo Oppong Nkrumah' },
  { id: 'okere', name: 'Okere', region: 'Eastern', party: 'NPP', mpName: 'Dan Botwe' },
  { id: 'suhum', name: 'Suhum', region: 'Eastern', party: 'NPP', mpName: 'Kojo Asante' },
  { id: 'upper-manya-krobo', name: 'Upper Manya Krobo', region: 'Eastern', party: 'NDC', mpName: 'Bismark Tetteh Nyarko' },
  { id: 'upper-west-akim', name: 'Upper West Akim', region: 'Eastern', party: 'NPP', mpName: 'Frederick Adom Obeng' },
  { id: 'yilo-krobo', name: 'Yilo Krobo', region: 'Eastern', party: 'NDC', mpName: 'Albert Tetteh Nyakotey' },

  // Central (23)
  { id: 'abura-asebu-kwamankese', name: 'Abura-Asebu-Kwamankese', region: 'Central', party: 'NDC', mpName: 'Elvis Morris Donkoh' },
  { id: 'agona-east', name: 'Agona East', region: 'Central', party: 'NDC', mpName: 'Queenstar Pokuah Sawyerr' },
  { id: 'agona-west', name: 'Agona West', region: 'Central', party: 'NPP', mpName: 'Cynthia Morrison' },
  { id: 'ajumako-enyan-essiam', name: 'Ajumako-Enyan-Essiam', region: 'Central', party: 'NDC', mpName: 'Cassiel Ato Forson' },
  { id: 'asikuma-odoben-brakwa', name: 'Asikuma-Odoben-Brakwa', region: 'Central', party: 'NDC', mpName: 'Alhaji Alhassan Kobina Ghansah' },
  { id: 'assin-central', name: 'Assin Central', region: 'Central', party: 'NPP', mpName: 'Kennedy Agyapong' },
  { id: 'assin-north', name: 'Assin North', region: 'Central', party: 'NDC', mpName: 'James Gyakye Quayson' },
  { id: 'assin-south', name: 'Assin South', region: 'Central', party: 'NPP', mpName: 'John Ntim Fordjour' },
  { id: 'awutu-senya-east', name: 'Awutu-Senya East', region: 'Central', party: 'NPP', mpName: 'Mavis Hawa Koomson' },
  { id: 'awutu-senya-west', name: 'Awutu-Senya West', region: 'Central', party: 'NDC', mpName: 'Gizella Tetteh Agbotui' },
  { id: 'cape-coast-north', name: 'Cape Coast North', region: 'Central', party: 'NDC', mpName: 'Kwamena Mintah Nyarku' },
  { id: 'cape-coast-south', name: 'Cape Coast South', region: 'Central', party: 'NDC', mpName: 'Kweku George Ricketts-Hagan' },
  { id: 'effutu', name: 'Effutu', region: 'Central', party: 'NPP', mpName: 'Alexander Afenyo-Markin' },
  { id: 'ekumfi', name: 'Ekumfi', region: 'Central', party: 'NDC', mpName: 'Abeiku Crentsil' },
  { id: 'gomoa-central', name: 'Gomoa Central', region: 'Central', party: 'NPP', mpName: 'Naana Eyiah Quansah' },
  { id: 'gomoa-east', name: 'Gomoa East', region: 'Central', party: 'NDC', mpName: 'Desmond De-Graft Paitoo' },
  { id: 'gomoa-west', name: 'Gomoa West', region: 'Central', party: 'NDC', mpName: 'Richard Gyan-Mensah' },
  { id: 'hemang-lower-denkyira', name: 'Hemang Lower Denkyira', region: 'Central', party: 'NPP', mpName: 'Bright Wireko Brobbey' },
  { id: 'komenda-edina-eguafo-abirem', name: 'Komenda-Edina-Eguafo-Abirem', region: 'Central', party: 'NDC', mpName: 'Samuel Atta Mills' },
  { id: 'mfantseman', name: 'Mfantseman', region: 'Central', party: 'NPP', mpName: 'Ophelia Hayford' },
  { id: 'twifo-atii-morkwaa', name: 'Twifo-Atii Morkwaa', region: 'Central', party: 'NDC', mpName: 'David Vondee' },
  { id: 'upper-denkyira-east', name: 'Upper Denkyira East', region: 'Central', party: 'NPP', mpName: 'Festus Awuah Kwofie' },
  { id: 'upper-denkyira-west', name: 'Upper Denkyira West', region: 'Central', party: 'NPP', mpName: 'Daniel Osei' },

  // Volta (18)
  { id: 'adaklu', name: 'Adaklu', region: 'Volta', party: 'NDC', mpName: 'Governs Kingsley Agbodza' },
  { id: 'afadzato-south', name: 'Afadzato South', region: 'Volta', party: 'NDC', mpName: 'Angela Oforiwaa Alorwu-Tay' },
  { id: 'agotime-ziope', name: 'Agotime-Ziope', region: 'Volta', party: 'NDC', mpName: 'Charles Agbeve' },
  { id: 'akatsi-north', name: 'Akatsi North', region: 'Volta', party: 'NDC', mpName: 'Peter Nortsu-Kotoe' },
  { id: 'akatsi-south', name: 'Akatsi South', region: 'Volta', party: 'NDC', mpName: 'Bernard Ahiafor' },
  { id: 'anlo', name: 'Anlo', region: 'Volta', party: 'NDC', mpName: 'Richard Sefe' },
  { id: 'central-tongu', name: 'Central Tongu', region: 'Volta', party: 'NDC', mpName: 'Alexander Roosevelt Hottordze' },
  { id: 'ho-central', name: 'Ho Central', region: 'Volta', party: 'NDC', mpName: 'Benjamin Komla Kpodo' },
  { id: 'ho-west', name: 'Ho West', region: 'Volta', party: 'NDC', mpName: 'Emmanuel Kwasi Bedzrah' },
  { id: 'hohoe', name: 'Hohoe', region: 'Volta', party: 'NPP', mpName: 'John Peter Amewu' },
  { id: 'keta', name: 'Keta', region: 'Volta', party: 'NDC', mpName: 'Kwame Dzudzorli Gakpey' },
  { id: 'ketu-north', name: 'Ketu North', region: 'Volta', party: 'NDC', mpName: 'James Klutse Avedzi' },
  { id: 'ketu-south', name: 'Ketu South', region: 'Volta', party: 'NDC', mpName: 'Dzifa Abla Gomashie' },
  { id: 'kpando', name: 'Kpando', region: 'Volta', party: 'NDC', mpName: 'Della Sowah' },
  { id: 'north-dayi', name: 'North Dayi', region: 'Volta', party: 'NDC', mpName: 'Joycelyn Tetteh' },
  { id: 'north-tongu', name: 'North Tongu', region: 'Volta', party: 'NDC', mpName: 'Samuel Okudzeto Ablakwa' },
  { id: 'south-dayi', name: 'South Dayi', region: 'Volta', party: 'NDC', mpName: 'Rockson-Nelson Dafeamekpor' },
  { id: 'south-tongu', name: 'South Tongu', region: 'Volta', party: 'NDC', mpName: 'Kobena Woyome' },

  // Northern (18)
  { id: 'bimbilla', name: 'Bimbilla', region: 'Northern', party: 'NPP', mpName: 'Dominic Nitiwul' },
  { id: 'gushegu', name: 'Gushegu', region: 'Northern', party: 'NPP', mpName: 'Alhassan Tampuli Sulemana' },
  { id: 'karaga', name: 'Karaga', region: 'Northern', party: 'NPP', mpName: 'Amin Anta Adam' },
  { id: 'kpandai', name: 'Kpandai', region: 'Northern', party: 'NDC', mpName: 'Daniel Nsula' },
  { id: 'kumbungu', name: 'Kumbungu', region: 'Northern', party: 'NDC', mpName: 'Dr. Hamza Adam' },
  { id: 'mion', name: 'Mion', region: 'Northern', party: 'NPP', mpName: 'Musah Abdul-Aziz Ayaba' },
  { id: 'nanton', name: 'Nanton', region: 'Northern', party: 'NPP', mpName: 'Hardi Tufeiru' },
  { id: 'saboba', name: 'Saboba', region: 'Northern', party: 'NPP', mpName: 'Charles Bintim' },
  { id: 'sagnarigu', name: 'Sagnarigu', region: 'Northern', party: 'NDC', mpName: 'Aba Alhassan' },
  { id: 'savelugu', name: 'Savelugu', region: 'Northern', party: 'NDC', mpName: 'Ibrahim Ibrahim' },
  { id: 'tamale-central', name: 'Tamale Central', region: 'Northern', party: 'NDC', mpName: 'Ibrahim Muhammed' },
  { id: 'tamale-north', name: 'Tamale North', region: 'Northern', party: 'NDC', mpName: 'Alhassan Suhuyini' },
  { id: 'tamale-south', name: 'Tamale South', region: 'Northern', party: 'NDC', mpName: 'Haruna Iddrisu' },
  { id: 'tatale-sanguli', name: 'Tatale-Sanguli', region: 'Northern', party: 'NPP', mpName: 'Tornam L. Kaboyee' },
  { id: 'tolon', name: 'Tolon', region: 'Northern', party: 'NPP', mpName: 'Habib Iddrisu' },
  { id: 'wulensi', name: 'Wulensi', region: 'Northern', party: 'NPP', mpName: 'Abukari Dawuni' },
  { id: 'yendi', name: 'Yendi', region: 'Northern', party: 'NPP', mpName: 'Farouk Aliu Mahama' },
  { id: 'zabzugu', name: 'Zabzugu', region: 'Northern', party: 'NPP', mpName: 'John Bennam' },

  // Western (17)
  { id: 'ahanta-west', name: 'Ahanta West', region: 'Western', party: 'NPP', mpName: 'Ebenezer Kojo Kum' },
  { id: 'amenfi-central', name: 'Amenfi Central', region: 'Western', party: 'NDC', mpName: 'Peter Yaw Kwakye-Ackah' },
  { id: 'amenfi-east', name: 'Amenfi East', region: 'Western', party: 'NDC', mpName: 'Nicholas Amankwah' },
  { id: 'amenfi-west', name: 'Amenfi West', region: 'Western', party: 'NDC', mpName: 'Eric Afful' },
  { id: 'effia', name: 'Effia', region: 'Western', party: 'NPP', mpName: 'Joseph Cudjoe' },
  { id: 'ellembelle', name: 'Ellembelle', region: 'Western', party: 'NDC', mpName: 'Emmanuel Armah-Kofi Buah' },
  { id: 'essikado-ketan', name: 'Essikado-Ketan', region: 'Western', party: 'NPP', mpName: 'Joe Ghartey' },
  { id: 'evalue-ajomoro-gwira', name: 'Evalue-Ajomoro-Gwira', region: 'Western', party: 'NDC', mpName: 'Kofi Arko Nokoe' },
  { id: 'jomoro', name: 'Jomoro', region: 'Western', party: 'NDC', mpName: 'Dorcas Toffey' },
  { id: 'kwesimintsim', name: 'Kwesimintsim', region: 'Western', party: 'NPP', mpName: 'Prince Hamidu Armah' },
  { id: 'mpohor', name: 'Mpohor', region: 'Western', party: 'NPP', mpName: 'Alex Kofi Agyekum' },
  { id: 'prestea-huni-valley', name: 'Prestea Huni-Valley', region: 'Western', party: 'NDC', mpName: 'Robert Wisdom Cudjoe' },
  { id: 'sekondi', name: 'Sekondi', region: 'Western', party: 'NPP', mpName: 'Andrew Egyapa Mercer' },
  { id: 'shama', name: 'Shama', region: 'Western', party: 'NPP', mpName: 'Erickson Abakah' },
  { id: 'takoradi', name: 'Takoradi', region: 'Western', party: 'NPP', mpName: 'Kwabena Okyere Darko-Mensah' },
  { id: 'tarkwa-nsuaem', name: 'Tarkwa-Nsuaem', region: 'Western', party: 'NPP', mpName: 'George Mireku Duker' },
  { id: 'wassa-east', name: 'Wassa East', region: 'Western', party: 'NDC', mpName: 'Isaac Adjei Mensah' },

  // Upper East (15)
  { id: 'bolgatanga-central', name: 'Bolgatanga Central', region: 'Upper East', party: 'NDC', mpName: 'Isaac Adongo' },
  { id: 'bolgatanga-east', name: 'Bolgatanga East', region: 'Upper East', party: 'NDC', mpName: 'Dominic Ayine' },
  { id: 'bongo', name: 'Bongo', region: 'Upper East', party: 'NDC', mpName: 'Edward Abambire Bawa' },
  { id: 'navrongo-central', name: 'Navrongo Central', region: 'Upper East', party: 'NDC', mpName: 'Sampson Chiragia' },
  { id: 'chiana-paga', name: 'Chiana-Paga', region: 'Upper East', party: 'NDC', mpName: 'Rudolf Amenga-Etego' },
  { id: 'builsa-north', name: 'Builsa North', region: 'Upper East', party: 'NDC', mpName: 'James Agalga' },
  { id: 'builsa-south', name: 'Builsa South', region: 'Upper East', party: 'NDC', mpName: 'Clement Apaak' },
  { id: 'talensi', name: 'Talensi', region: 'Upper East', party: 'NDC', mpName: 'Benson Tongo Baba' },
  { id: 'nabdam', name: 'Nabdam', region: 'Upper East', party: 'NDC', mpName: 'Mark Kurt Nawaane' },
  { id: 'bawku-central', name: 'Bawku Central', region: 'Upper East', party: 'NDC', mpName: 'Mahama Ayariga' },
  { id: 'pusiga', name: 'Pusiga', region: 'Upper East', party: 'NDC', mpName: 'Laadi Ayii Ayamba' },
  { id: 'garu', name: 'Garu', region: 'Upper East', party: 'NDC', mpName: 'Albert Alalzuuga Akuka' },
  { id: 'tempane', name: 'Tempane', region: 'Upper East', party: 'NDC', mpName: 'Lydia Akanvariba Lamisi' },
  { id: 'binduri', name: 'Binduri', region: 'Upper East', party: 'NPP', mpName: 'Abdulai Abanga' },
  { id: 'zebilla', name: 'Zebilla', region: 'Upper East', party: 'NDC', mpName: 'Cletus Apul Avoka' },

  // Bono (12)
  { id: 'sunyani-west', name: 'Sunyani West', region: 'Bono', party: 'NPP', mpName: 'Ignatius Baffour Awuah' },
  { id: 'sunyani-east', name: 'Sunyani East', region: 'Bono', party: 'NPP', mpName: 'Kwasi Ameyaw-Cheremeh' },
  { id: 'berekum-east', name: 'Berekum East', region: 'Bono', party: 'NPP', mpName: 'Nelson Kyeremeh' },
  { id: 'berekum-west', name: 'Berekum West', region: 'Bono', party: 'NPP', mpName: 'Kwaku Agyenim-Boateng' },
  { id: 'dormaa-central', name: 'Dormaa Central', region: 'Bono', party: 'NPP', mpName: 'Kwaku Agyeman-Manu' },
  { id: 'dormaa-east', name: 'Dormaa East', region: 'Bono', party: 'NPP', mpName: 'Paul Apreku Twum-Barimah' },
  { id: 'dormaa-west', name: 'Dormaa West', region: 'Bono', party: 'NDC', mpName: 'Vincent Oppong Asamoah' },
  { id: 'jaman-north', name: 'Jaman North', region: 'Bono', party: 'NDC', mpName: 'Frederick Yaw Ahenkwah' },
  { id: 'jaman-south', name: 'Jaman South', region: 'Bono', party: 'NDC', mpName: 'Williams Okofo-Dateh' },
  { id: 'wenchi', name: 'Wenchi', region: 'Bono', party: 'NDC', mpName: 'Haruna Seidu' },
  { id: 'banda', name: 'Banda', region: 'Bono', party: 'NDC', mpName: 'Ahmed Ibrahim' },
  { id: 'tain', name: 'Tain', region: 'Bono', party: 'NDC', mpName: 'Adama Sulemana' },

  // Bono East (11)
  { id: 'techiman-south', name: 'Techiman South', region: 'Bono East', party: 'NPP', mpName: 'Martin Adjei-Mensah Korsah' },
  { id: 'techiman-north', name: 'Techiman North', region: 'Bono East', party: 'NDC', mpName: 'Elizabeth Ofosu-Adjare' },
  { id: 'kintampo-south', name: 'Kintampo South', region: 'Bono East', party: 'NDC', mpName: 'Felicia Adjei' },
  { id: 'kintampo-north', name: 'Kintampo North', region: 'Bono East', party: 'NDC', mpName: 'Joseph Kwame Kumah' },
  { id: 'nkoranza-south', name: 'Nkoranza South', region: 'Bono East', party: 'NDC', mpName: 'Emmanuel Kwadwo Agyekum' },
  { id: 'nkoranza-north', name: 'Nkoranza North', region: 'Bono East', party: 'NDC', mpName: 'Joseph Mensah' },
  { id: 'atebubu-amantin', name: 'Atebubu-Amantin', region: 'Bono East', party: 'NDC', mpName: 'Sanja Nanja' },
  { id: 'pru-west', name: 'Pru West', region: 'Bono East', party: 'NPP', mpName: 'Stephen Pambiin Jalulah' },
  { id: 'pru-east', name: 'Pru East', region: 'Bono East', party: 'NDC', mpName: 'Dr. Kwabena Donkor' },
  { id: 'sene-west', name: 'Sene West', region: 'Bono East', party: 'NDC', mpName: 'Kwame Ampofo Twumasi' },
  { id: 'sene-east', name: 'Sene East', region: 'Bono East', party: 'NDC', mpName: 'Dominic Napare' },

  // Upper West (11)
  { id: 'wa-central', name: 'Wa Central', region: 'Upper West', party: 'NDC', mpName: 'Abdul-Rashid Hassan Pelpuo' },
  { id: 'wa-east', name: 'Wa East', region: 'Upper West', party: 'NDC', mpName: 'Godfred Seidu Jasaw' },
  { id: 'wa-west', name: 'Wa West', region: 'Upper West', party: 'NDC', mpName: 'Peter Lanchene Toobu' },
  { id: 'nadowli-kaleo', name: 'Nadowli Kaleo', region: 'Upper West', party: 'NDC', mpName: 'Anthony Sumah Mwinikaara' },
  { id: 'jirapa', name: 'Jirapa', region: 'Upper West', party: 'NDC', mpName: 'Cletus Seidu Dapilah' },
  { id: 'lambussie', name: 'Lambussie', region: 'Upper West', party: 'NPP', mpName: 'Bakye Yelviel Baligi' },
  { id: 'lawra', name: 'Lawra', region: 'Upper West', party: 'NDC', mpName: 'Bede A. Ziedeng' },
  { id: 'nandom', name: 'Nandom', region: 'Upper West', party: 'NPP', mpName: 'Ambrose Dery' },
  { id: 'sissala-east', name: 'Sissala East', region: 'Upper West', party: 'NPP', mpName: 'Amidu Chinia Issahaku' },
  { id: 'sissala-west', name: 'Sissala West', region: 'Upper West', party: 'NDC', mpName: 'Mohammed Adams Sukparu' },
  { id: 'daffiama-bussie-issa', name: 'Daffiama Bussie Issa', region: 'Upper West', party: 'NDC', mpName: 'Sebastian Sandaare' },

  // Western North (9)
  { id: 'sefwi-wiawso', name: 'Sefwi Wiawso', region: 'Western North', party: 'NPP', mpName: 'Dr. Kwaku Afriyie' },
  { id: 'sefwi-akontombra', name: 'Sefwi Akontombra', region: 'Western North', party: 'NPP', mpName: 'Alex Djonoboah Tetteh' },
  { id: 'juabeso', name: 'Juabeso', region: 'Western North', party: 'NDC', mpName: 'Kwabena Mintah Akandoh' },
  { id: 'bodi', name: 'Bodi', region: 'Western North', party: 'NDC', mpName: 'Sampson Ahi' },
  { id: 'bia-west', name: 'Bia West', region: 'Western North', party: 'NDC', mpName: 'Augustine Tawiah' },
  { id: 'bia-east', name: 'Bia East', region: 'Western North', party: 'NDC', mpName: 'Richard Acheampong' },
  { id: 'suaman', name: 'Suaman', region: 'Western North', party: 'NDC', mpName: 'Joseph Betino' },
  { id: 'aowin', name: 'Aowin', region: 'Western North', party: 'NDC', mpName: 'Oscar Larbi' },
  { id: 'bibiani-anhwiaso-bekwai', name: 'Bibiani Anhwiaso Bekwai', region: 'Western North', party: 'NPP', mpName: 'Alfred Obeng-Boateng' },

  // Oti (8)
  { id: 'krachi-west', name: 'Krachi West', region: 'Oti', party: 'NDC', mpName: 'Helen Adjoa Ntoso' },
  { id: 'krachi-east', name: 'Krachi East', region: 'Oti', party: 'NPP', mpName: 'Michael Yaw Gyato' },
  { id: 'krachi-nchumuru', name: 'Krachi Nchumuru', region: 'Oti', party: 'NDC', mpName: 'Solomon Kuyon' },
  { id: 'nkwanta-north', name: 'Nkwanta North', region: 'Oti', party: 'NDC', mpName: 'John Oti Bless' },
  { id: 'nkwanta-south', name: 'Nkwanta South', region: 'Oti', party: 'NDC', mpName: 'Geoffrey Kini' },
  { id: 'biakoye', name: 'Biakoye', region: 'Oti', party: 'NDC', mpName: 'Kwadwo Nyanpon Aboagye' },
  { id: 'kadjebi', name: 'Kadjebi', region: 'Oti', party: 'NDC', mpName: 'Yao Gomado' },
  { id: 'guan', name: 'Guan', region: 'Oti', party: 'NDC', mpName: 'Fred Kwasi Amankwah-Asare' },

  // Savannah (7)
  { id: 'damongo', name: 'Damongo', region: 'Savannah', party: 'NPP', mpName: 'Samuel Abu Jinapor' },
  { id: 'bole-bamboi', name: 'Bole Bamboi', region: 'Savannah', party: 'NDC', mpName: 'Yusif Sulemana' },
  { id: 'sawla-tuna-kalba', name: 'Sawla Tuna Kalba', region: 'Savannah', party: 'NDC', mpName: 'Andrew Dari Chiwitey' },
  { id: 'salaga-south', name: 'Salaga South', region: 'Savannah', party: 'NDC', mpName: 'Zuwera Mohammed Ibrahimah' },
  { id: 'salaga-north', name: 'Salaga North', region: 'Savannah', party: 'NDC', mpName: 'Alhassan Abdallah Iddi' },
  { id: 'yapei-kusawgu', name: 'Yapei Kusawgu', region: 'Savannah', party: 'NDC', mpName: 'John Abdulai Jinapor' },
  { id: 'daboya-mankarigu', name: 'Daboya Mankarigu', region: 'Savannah', party: 'NPP', mpName: 'Alhaji Asei Mahama Seini' },

  // Ahafo (6)
  { id: 'asunafo-north', name: 'Asunafo North', region: 'Ahafo', party: 'NPP', mpName: 'Evans Bobie Opoku' },
  { id: 'asunafo-south', name: 'Asunafo South', region: 'Ahafo', party: 'NDC', mpName: 'Eric Opoku' },
  { id: 'asutifi-north', name: 'Asutifi North', region: 'Ahafo', party: 'NPP', mpName: 'Patrick Banimah' },
  { id: 'asutifi-south', name: 'Asutifi South', region: 'Ahafo', party: 'NDC', mpName: 'Collins Dauda' },
  { id: 'tano-north', name: 'Tano North', region: 'Ahafo', party: 'NPP', mpName: 'Freda Prempeh' },
  { id: 'tano-south', name: 'Tano South', region: 'Ahafo', party: 'NPP', mpName: 'Benjamin Yeboah Sekyere' },

  // North East (6)
  { id: 'nalerigu-gambaga', name: 'Nalerigu Gambaga', region: 'North East', party: 'NDC', mpName: 'Baba Seidu Issifu' },
  { id: 'walewale', name: 'Walewale', region: 'North East', party: 'NPP', mpName: 'Lariba Zuweira Abudu' },
  { id: 'yagaba-kubori', name: 'Yagaba Kubori', region: 'North East', party: 'NPP', mpName: 'Mustapha Ussif' },
  { id: 'bunkpurugu', name: 'Bunkpurugu', region: 'North East', party: 'NPP', mpName: 'Abene Abayage' },
  { id: 'yunyoo', name: 'Yunyoo', region: 'North East', party: 'NPP', mpName: 'Oscar Liwaal' },
  { id: 'chereponi', name: 'Chereponi', region: 'North East', party: 'NDC', mpName: 'Abdul-Razak Tahidu' }
];

module.exports = CONSTITUENCIES;
